eTickets/Controllers/BookmarksController.cs
using eTickets.Data.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    [Authorize]
    public class BookmarksController : Controller
    {
        private readonly IBookmarksService _bookmarksService;
        private readonly IToursService _toursService;
        public BookmarksController(IBookmarksService bookmarksService, IToursService toursService)
        {
            _bookmarksService = bookmarksService;
            _toursService = toursService;
        }
        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var bookmarks = await _bookmarksService.GetUserBookmarksAsync(userId);
            return View(bookmarks);
        }

        public async Task<IActionResult> AddUserBookmark(int id)
        {
            var item = await _toursService.GetByIdAsync(id);
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            

            if (item != null)
            {
               await  _bookmarksService.AddUserBookmark(userId, item);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteUserBookmark(int id)
        {
            var item = await _toursService.GetByIdAsync(id);
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (item != null)
            {
                await _bookmarksService.DeleteUserBookmark(userId, item);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

eTickets/Controllers/OrdersController.cs
using eTickets.Data.Services;
using eTickets.Data.Static;
using eTickets.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IToursService _toursService;
        private readonly IOrdersService _ordersService;

        public OrdersController(IToursService toursService, IOrdersService ordersService)
        {
            _toursService = toursService;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }

        public async Task<IActionResult> Create(int tourId)
        {
            var tour = await _toursService.GetTourByIdAsync(tourId);

            var orderVM = new OrderVM()
            {
                TourId = tourId,
                TourName = tour.Name
            };

            return View(orderVM);
        }

        [HttpPost]
        public async Task<IActionResult> Create(OrderVM orderVm)
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            await _ordersService.CreateOrderAsync(userId, orderVm);

            return View("OrderCompleted");
        }

        public async Task<IActionResult> Edit(int id)
        {
            var order = await _ordersService.GetOrderWithHistoryAndTourInfoAsync(id);

            var orderVM = new OrderVM()
            {
                Id = order.Id,
                TourId = order.TourId,
                TourName = order.Tour.Name,
                ContactEmail = order.ContactEmail,
                ContactPhone = order.ContactPhone,
                PersonQuantity = order.PersonQuantity,
                OrderStatus = order.OrderHistoryItems.OrderByDescending(x => x.CreateDate).First().OrderStatus,
            };

            return View(orderVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, OrderVM orderVm)
        {
            if (id != orderVm.Id) return View("NotFound");

            await _ordersService.UpdateOrderAsync(id, orderVm);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Reject(int id)
        {
            var order = await _ordersService.GetOrderWithHistoryAndTourInfoAsync(id);

            var orderVM = new OrderVM()
            {
                Id = order.Id,
            };

            ViewData["CancellationType"] = "Reject";
            return View("Cancel", orderVM);
        }

        [HttpPost]
        public async Task<IActionResult> Reject(int id, OrderVM orderVm)
        {
            if (id != orderVm.Id) return View("NotFound");

            await _ordersService.RejectOrderAync(id, orderVm.Comment);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Cancel(int id)
        {
            var order = await _ordersService.GetOrderWithHistoryAndTourInfoAsync(id);

            var orderVM = new OrderVM()
            {
                Id = order.Id,
            };

            ViewData["CancellationType"] = "Cancel";
            return View(orderVM);
        }

        [HttpPost]
        public async Task<IActionResult> Cancel(int id, OrderVM orderVm)
        {
            if (id != orderVm.Id) return View("NotFound");

            await _ordersService.CancelOrderAsync(id, orderVm.Comment);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Confirm(int id)
        {
            var order = await _ordersService.GetOrderWithHistoryAndTourInfoAsync(id);

            var orderVM = new OrderVM()
            {
                Id = order.Id,
                ContactEmail = order.ContactEmail,
                ContactPhone = order.ContactPhone,
                TourName = order.Tour.Name,
            };

            return View(orderVM);
        }

        [HttpPost]
        public async Task<IActionResult> Confirm(int id, OrderVM orderVm)
        {
            if (id != orderVm.Id) return View("NotFound");

            await _ordersService.ConfirmOrderAsync(id, orderVm.Comment);

            return RedirectToAction("Index");
        }
    }
}

eTickets/Controllers/ToursController.cs
using eTickets.Data;
using eTickets.Data.Services;
using eTickets.Data.Static;
using eTickets.Data.ViewModels;
using eTickets.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    [Authorize(Roles = "Admin, Manager")]
    public class ToursController : Controller
    {
        private readonly IToursService _service;
        private readonly IBookmarksService _bookmarksService;
        private readonly ITravelManagerService _travelManagerService;

        public ToursController(IToursService service, IBookmarksService bookmarksService, ITravelManagerService travelManagerService)
        {
            _service = service;
            _bookmarksService = bookmarksService;
            _travelManagerService = travelManagerService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var allTours = await _service.GetAllAsync(n => n.TravelAgency);
            if (userRole == UserRoles.Manager)
            {
                var travelAgencyId = await _travelManagerService.GetTravelAgencyIdByManagerUserId(userId);
                allTours = allTours.Where(n => n.TravelAgencyId == travelAgencyId);
            }
           

            //bookmarks check
            var bookmarks = await _bookmarksService.GetUserBookmarksAsync(userId);

            var bookmarkedTours = new List<Tour>();
            foreach(var tour in allTours)
            {
                if(bookmarks.Any(x => x.Tour == tour))
                {
                    bookmarkedTours.Add(tour);
                }
            }
            ViewData["BookmarkedTours"] = bookmarkedTours;
            return View(allTours);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Filter(string searchString)
        {
            var allTours = await _service.GetAllAsync(n => n.TravelAgency);

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResultNew = allTours.Where(n => n.Name.ToLower().Contains(searchString.ToLower()) || n.Description.ToLower().Contains(searchString.ToLower())).ToList();

                string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

                var bookmarks = await _bookmarksService.GetUserBookmarksAsync(userId);

                var bookmarkedTours = new List<Tour>();
                foreach (var tour in allTours)
                {
                    if (bookmarks.Any(x => x.Tour == tour))
                    {
                        bookmarkedTours.Add(tour);
                    }
                }
                ViewData["BookmarkedTours"] = bookmarkedTours;

                //var filteredResultNew = allTours.Where(n => string.Equals(n.Name, searchString, StringComparison.CurrentCultureIgnoreCase) || string.Equals(n.Description, searchString, StringComparison.CurrentCultureIgnoreCase)).ToList();

                return View("Index", filteredResultNew);
            }

            return View("Index", allTours);
        }

        [AllowAnonymous]
        public async Task<IActionResult> SortByPrice()
        {
            var allTours = await _service.GetAllAsync(n => n.TravelAgency);

                //var filteredResult = allTours.Where(n => n.Name.ToLower().Contains(searchString.ToLower()) || n.Description.ToLower().Contains(searchString.ToLower())).ToList();


            var filteredResultNew = allTours.OrderBy(x => x.Price).ToList();

            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var bookmarks = await _bookmarksService.GetUserBookmarksAsync(userId);

            var bookmarkedTours = new List<Tour>();
            foreach (var tour in allTours)
            {
                if (bookmarks.Any(x => x.Tour == tour))
                {
                    bookmarkedTours.Add(tour);
                }
            }
            ViewData["BookmarkedTours"] = bookmarkedTours;

            return View("Index", filteredResultNew);
        }

        //GET: Tours/Details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var tourDetail = await _service.GetTourByIdAsync(id);
            return View(tourDetail);
        }

        //GET: Tours/Create
        public async Task<IActionResult> Create()
        {
            var tourDropdownsData = await _service.GetNewTourDropdownsValues();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            if (userRole == UserRoles.Manager)
            {
                var travelAgencyId = await _travelManagerService.GetTravelAgencyIdByManagerUserId(userId);
                tourDropdownsData.TravelAgencies.RemoveAll(x => x.Id != travelAgencyId);
            }
            ViewBag.TravelAgencies = new SelectList(tourDropdownsData.TravelAgencies, "Id", "Name");
            ViewBag.Countries = new SelectList(tourDropdownsData.Countries, "Id", "CountryName");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewTourVM tour)
        {
            if (!ModelState.IsValid)
            {
                var tourDropdownsData = await _service.GetNewTourDropdownsValues();
                string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                string userRole = User.FindFirstValue(ClaimTypes.Role);
                if (userRole == UserRoles.Manager)
                {
                    var travelAgencyId = await _travelManagerService.GetTravelAgencyIdByManagerUserId(userId);
                    tourDropdownsData.TravelAgencies.RemoveAll(x => x.Id != travelAgencyId);
                }
                ViewBag.TravelAgencies = new SelectList(tourDropdownsData.TravelAgencies, "Id", "Name");
                ViewBag.Countries = new SelectList(tourDropdownsData.Countries, "Id", "CountryName");

                return View(tour);
            }

            await _service.AddNewTourAsync(tour);
            return RedirectToAction(nameof(Index));
        }


        //GET: Tours/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var tourDetails = await _service.GetTourByIdAsync(id);
            if (tourDetails == null) return View("NotFound");

            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var response = new NewTourVM()
            {
                Id = tourDetails.Id,
                Name = tourDetails.Name,
                Description = tourDetails.Description,
                Price = tourDetails.Price,
                StartDate = tourDetails.StartDate,
                EndDate = tourDetails.EndDate,
                ImageURL = tourDetails.ImageURL,
                TourCategory = tourDetails.TourCategory,
                TravelAgencyId = tourDetails.TravelAgencyId,
                CountryIds = tourDetails.Countries_Tours.Select(n => n.CountryId).ToList(),
            };

            var tourDropdownsData = await _service.GetNewTourDropdownsValues();
            if (userRole == UserRoles.Manager)
            {
                var travelAgencyId = await _travelManagerService.GetTravelAgencyIdByManagerUserId(userId);
                tourDropdownsData.TravelAgencies.RemoveAll(x => x.Id != travelAgencyId);
            }
            ViewBag.TravelAgencies = new SelectList(tourDropdownsData.TravelAgencies, "Id", "Name");
            ViewBag.Countries = new SelectList(tourDropdownsData.Countries, "Id", "CountryName");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewTourVM tour)
        {
            if (id != tour.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var tourDropdownsData = await _service.GetNewTourDropdownsValues();
                string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                string userRole = User.FindFirstValue(ClaimTypes.Role);
                if (userRole == UserRoles.Manager)
                {
                    var travelAgencyId = await _travelManagerService.GetTravelAgencyIdByManagerUserId(userId);
                    tourDropdownsData.TravelAgencies.RemoveAll(x => x.Id != travelAgencyId);
                }
                ViewBag.TravelAgencies = new SelectList(tourDropdownsData.TravelAgencies, "Id", "Name");
                ViewBag.Countries = new SelectList(tourDropdownsData.Countries, "Id", "CountryName");

                return View(tour);
            }

            await _service.UpdateTourAsync(tour);
            return RedirectToAction(nameof(Index));
        }
    }
}

eTickets/Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
        <h1 class="text-info">You've reached the end of the internet</h1>
        <hr />
        <a class="btn btn-outline-success" asp-controller="Tours" asp-action="Index">Home Page</a>
    </div>
</div>

eTickets/Views/Shared/_CreateItem.cshtml
@model string;

@if (User.Identity.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Manager")))
{
    <div style="position: fixed; right: 25px; bottom: 25px;" class="text-white">
        <a asp-controller="@Model" asp-action="Create" class="btn btn-success">
            <i class="bi bi-plus-circle"></i> Add New
        </a>
    </div>
}

eTickets/Views/Shared/_Identity.cshtml
@inject UserManager<ApplicationUser> UserManager; 

@if (!User.Identity.IsAuthenticated)
{
    <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i> Log in
    </a>
    <span style="padding: 5px;"></span>

    <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
        <i class="bi bi-person-plus"></i> Register
    </a>
}
else
{

    @*User profile section*@
    <div class="dropdown">
        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown"
                aria-expanded="false">
            <i class="bi bi-person-badge"></i> Hello @UserManager.GetUserName(User)
        </button>
        <ul class="dropdown-menu" aria-labelledby="profile-btn">
            @if (User.IsInRole("User"))
            {
                <li>
                    <a class="dropdown-item" asp-controller="Orders" asp-action="Index">
                    <i class="bi bi-list"></i> My Orders
                </a>
                </li>
            }
        </ul>
    </div>
    <span style="padding: 5px;"></span>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i> Log out
        </button>
    </form>
}

eTickets/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eTickets</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Tours" asp-action="Index">eTickets</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tours" asp-action="Index"><i class="bi bi-sun"></i> Tours</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bookmarks" asp-action="Index"><i class="bi bi-bookmark"></i> Bookmarks</a>
                        </li>

                        @if(User.Identity.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Manager")))
                        {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="bi bi-gear"></i> Management
                                    </a>
                                @if(User.IsInRole("Admin"))
                                {
                                     <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" asp-controller="TravelAgencies" asp-action="Index"><i class="bi bi-briefcase"></i> Travel Agencies</a>
                                        <a class="dropdown-item" asp-controller="Countries" asp-action="Index"><i class="bi bi-flag"></i> Countries</a>
                                        <a class="dropdown-item" asp-controller="Account" asp-action="Users"><i class="bi bi-people"></i> Users</a>
                                        <a class="dropdown-item" asp-controller="Orders" asp-action="Index"><i class="bi bi-file-earmark"></i> Orders</a>
                                    </div>
                                }
                                @if(User.IsInRole("Manager"))
                                {
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" asp-controller="TravelAgencies" asp-action="Index"><i class="bi bi-briefcase"></i> My Agency</a>
                                        <a class="dropdown-item" asp-controller="Orders" asp-action="Index"><i class="bi bi-file-earmark"></i> Orders</a>
                                    </div>
                                }

                                </li>
                        }   
                    </ul>

                    <form class="form-inline my-2 my-lg-0" asp-controller="Tours" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a tour..." aria-label="Recipient's username" aria-describedby="button-addon2">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>

                    <partial name="_Identity.cshtml" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Travelo
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>